# Generated by Django 3.2.8 on 2021-10-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pos', models.FloatField()),
                ('neg', models.FloatField()),
                ('neu', models.FloatField()),
                ('compound', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.excelfile')),
            ],
        ),
    ]
